services:
  gemma-3-1b-executor:
    image: kuwaai/model-executor
    environment:
      EXECUTOR_TYPE: llamacpp
      EXECUTOR_ACCESS_CODE: .model/google/gemma-1b-it
      EXECUTOR_NAME: Gemma 3 1B
      EXECUTOR_IMAGE: gemma.png # Refer to src/multi-chat/public/images
      EXECUTOR_ORDER: 311003
      HUGGING_FACE_HUB_TOKEN: ${HUGGING_FACE_HUB_TOKEN}
    depends_on:
      - executor-builder
      - kernel
      - multi-chat
    command: [
      "--model_path", "hf://tetf/gemma-3-1b-it-qat-q4_0-GGUF?gemma-3-1b-it-q4_0.gguf",
      "--visible_gpu", "0",
      "--log", "debug"
    ]
    restart: unless-stopped
    volumes: ["~/.cache/huggingface:/root/.cache/huggingface"]
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    networks: ["backend"]
