services:
  custom-dbqa-executor:
    extends:
      file: executor_base.yaml
      service: executor-base
    depends_on:
      - executor-builder
    environment:
      CUSTOM_EXECUTOR_PATH: ./docqa/docqa.py
      EXECUTOR_ACCESS_CODE: db-qa:custom-db
      EXECUTOR_NAME: DB QA (Custom DB)
      TRANSFORMERS_OFFLINE: ${TRANSFORMERS_OFFLINE:-0} # For embedding model
    volumes: [
      "</path/to/vector-database>:/var/database/",
    ]
    command: [
      "--api_base_url", "http://web/",
      "--model", ".bot/.default",
      "--database", "/var/database/",
      "--log", "debug"
      ]