services:
  gemini-executor:
    extends:
      file: executor_base.yaml
      service: executor-base
    depends_on:
      - executor-builder
    environment:
      EXECUTOR_TYPE: geminipro
      EXECUTOR_ACCESS_CODE: .model/google/gemini
      EXECUTOR_NAME: Gemini
      EXECUTOR_IMAGE: gemini.png # Refer to src/multi-chat/public/images
      EXECUTOR_ORDER: 401000
    command: [
      #"--api_key", "<YOUR_GLOBAL_API_KEY_HERE>",
      "--log", "debug"
    ]